### ISSUE TITLE
`new_honeycomb_telemetry_layer` reports 0% of spans

### ISSUE THREAD

**Issue by henriiik** [eaze/tracing-honeycomb#4]
Before #1 a TelemetryLayer created with `eaze_tracing_honeycomb::new_honeycomb_telemetry_layer` would report 100% of all spans, but after it does not report any at all. It was quite confusing when migrating from `inanna-malick/tracing-honeycomb`. Is the new behaviour intended?

Either way the trace-level sampling looks great, well done!

**Comment by Fishrock123** [comment]
The bug is here: https://github.com/eaze/tracing-honeycomb/pull/1/files#diff-a6d41a7f5e4676085d87156aedec476bd27839aa5c13dbba5ac4f91518ac06fdR57

**Comment by Fishrock123** [comment]
Fixed in eaze-tracing-honeycomb `0.2.1-eaze.4`.

**Comment by henriiik** [comment]
Thank You! 🙏🏻
