### ISSUE TITLE
AWS Lambda Instrumentation

### ISSUE THREAD

**Issue by rasviitanen** [eaze/tracing-honeycomb#5]
We ran into some issues running tracing-honeycomb on AWS lambda.

Basically we experienced two problems:

1. Lambda functions resolves once it replies to the requestee, so libhoney would need flush its queued events before a response can be sent. This can take a while and lead to poor performance, as flushing libhoney is not instant.
2. libhoney does not handle flushing of queued events very well  (https://github.com/nlopes/libhoney-rust/issues/65). 

Luckily, Honeycomb provides a layer that fixes this: https://docs.honeycomb.io/getting-data-in/integrations/aws/aws-lambda/

To make it work with tracing-honeycomb, it would need to send its spans to `stdout` instead of a libhoney client.

--- 

We have been working on a fix that makes the `HoneycombTelemetry` generic over some `Reporter`, where you can pick either Stdout/Libhoney via a builder.

Is this something you would like to see added to this repository?
We would be happy to add our implementation if so.

**Comment by Fishrock123** [comment]
Yes please. We'd like to run rust lambdas in the near future as well and this would be very much appreciated!

**Comment by Fishrock123** [comment]
Released in 0.4.1: https://github.com/eaze/tracing-honeycomb/releases/tag/tracing-honeycomb-0.4.1

(I yanked 0.4.0 due to the wrong git commit)
